#!/usr/bin/env python

# import os
import sys
from datetime import datetime

from pyscf import __version__

sys.path.append("./source/tools/extensions")

# -- Sphinx Options -----------------------------------------------------------

# If your project needs a minimal Sphinx version, state it here.
needs_sphinx = "1.2"

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.extlinks",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.mathjax",
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
    "sphinxcontrib.bibtex",
    "nbsphinx",
    "pyscfdocext",
    "myst_parser",
    "sphinx_design",
    "gallery_directive",
]
bibtex_bibfiles = ['user/ref.bib']
myst_update_mathjax = False
myst_enable_extensions = [
    "colon_fence",
    "dollarmath",
]


# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = "index"

# General information about the project.
project = u"PySCF"
year = datetime.now().year
copyright = f"{year}, The PySCF Developers"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#

# The short X.Y version.
v,sv = __version__.split('.')[:2]
version = "%s.%s"%(v,sv)
# The full version, including alpha/beta/rc tags.
release = __version__


# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["modules/*"]

# The reST default role (used for this markup: `text`) to use for all
# documents.
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "default"

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]


# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#html_theme = "sphinx_material"
html_theme = "pydata_sphinx_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.

if html_theme == 'sphinx_material':
    html_css_files = ["css/pyscf-material.css"]
    html_theme_options = {
        # "github_button": False,
        "repo_name": "PySCF",
        "repo_url": "https://github.com/pyscf/pyscf/",
        "nav_title": "PySCF {0}".format(version),
        #"color_primary": "blue",
        #"color_accent": "amber",
        "color_primary": "pyscf",
        "color_accent": "pyscf",
        "globaltoc_depth": 2,
        "globaltoc_collapse": True,
        "master_doc": False,
        "heroes": {"index": "The Python-based Simulations of Chemistry Framework"},
        "nav_links": [
            {"href": "index", "title": "Home", "internal": True},
            #{"href": "overview", "title": "Overview", "internal": True},
            {"href": "install", "title": "Install", "internal": True},
            {"href": "quickstart", "title": "Quickstart", "internal": True},
            {"href": "user", "title": "User Guide", "internal": True},
            {"href": "develop", "title": "Developer Guide", "internal": True},
            {"href": "pyscf_api_docs/modules", "title": "API", "internal": True},
            {"href": "about", "title": "About", "internal": True},
        ],
        "table_classes": ["simple"],
    }

    # The name of an image file (relative to this directory) to place at the top
    # of the sidebar.
    html_logo = "../logo/pyscf-logo-white.svg"


if html_theme == 'pydata_sphinx_theme':
    html_css_files = ["css/pyscf-pst.css"]
    html_context = {
        "github_user": "pyscf",
        "github_repo": "pyscf.github.io",
        "github_version": "master",
        "doc_path": "source",
    }

    html_theme_options = {
        "logo": {
            "text": "PySCF",
            "image_light": "../logo/logo-64x64.png",
            "image_dark": "../logo/logo-64x64.png",
        },
        "icon_links": [
            {
                "name": "GitHub",
                "url": "https://github.com/pyscf/pyscf",
                "icon": "fa-brands fa-github",
                "type": "fontawesome",
            },
        ],
        "use_edit_page_button": True,
        "show_toc_level": 1,
        "secondary_sidebar_items": {
            "**": ["page-toc", "edit-this-page"],
        },
        # "navbar_align": "left",
    }

html_sidebars = {
  "install": [],
  "quickstart": [],
  "about": [],
}


# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = [alabaster.get_path()]

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = "PySCF" 

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = "PySCF" 

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "../logo/favicon-32x32.png"

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
# html_domain_indices = True

# If false, no index is generated.
# html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr'
# html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
# html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
# html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = "PySCFdoc"
